<?php

global $user;
/**
* @file
* Menu Forcontu
* Forcontu - Ejemplos de formulario
*/


/**
* Implements hook_menu().
*/
function forms_forcontu_menu() {

	$items['formulario/oferta'] = array(
	'title' => t('Offers form for authenticated users'),
	'page callback' => 'drupal_get_form',
	'page arguments' => array('offers_form'),
	'access callback' => 'user_access',
	'access arguments' => array('make an offer'),
	//'access callback' => 'forms_forcontu_view_access',
	'description' => t('Offers Form'),
	'type' => MENU_LOCAL_TASK,

	);

	$items['admin/config/workflow/ofertas_formulario'] = array(
		'title' => 'Node Offers Form settings',
		'description' => 'Settings for module Offers form ',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('offers_form_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'forms_forcontu.admin.inc',
	);

	$items['admin/structure/type/instrumentos'] = array(
		'title' => 'Instruments Management',
		'description' => 'Settings the Instrument table content ',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('instruments_form_admin_settings'),
		'access arguments' => array('administer content types'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'forms_forcontu_instrumentos.admin.inc',
	);

	$items['ofertas/%/user/%user/detalle'] = array(
		'title' => t('Detalle de la oferta'),
		//'type' => MENU_LOCAL_TASK,
		//'type' => MENU_CALLBACK,
		'access callback' => 'user_access',
		'access arguments' => array('make an offer'),
		'page callback' => 'drupal_get_form',
		//'page callback' => 'forms_ofertas_detalle',
		'page arguments' => array('forms_ofertas_detalle',1),
	);
	$items['ofertas/%/user/%user/detalle/view'] = array(
		'title' => 'View offer',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 1,
	);


	$items['ofertas/%/user/%user/detalle/edit'] = array(
		'title' => t('Edit offer'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('forms_ofertas_detalle_edit',1),
		'access callback' => 'user_edit_access',
		//'access callback' => 'ofertas_edit_access',
		'access arguments' => array(3),
		'description' => t('Offer edit'),
		'type' => MENU_LOCAL_TASK,
		'weight' => 2,

	);
	$items['ofertas/ver/detalle/confirm'] = array(
		'title' => t('Confirmación de la suscripción'),
		'type' => MENU_CALLBACK,
		'access callback' => TRUE,
		'page callback' => 'drupal_get_form',
		//'page callback' => 'forms_ofertas_detalle',
		'page arguments' => array('forms_ofertas_detalle_confirm'),
	);


	//Pestañas para el listado
	$items['listado'] = array(
	'title' => t('Listado de ofertas'),
		//'page callback' => 'drupal_get_form',
		'page callback' => 'forms_ofertas_listado',
		'page arguments' => array('forms_ofertas_listado'),
		'access callback' => TRUE,
		'description' => t('Listado de ofertas'),
		'type' => MENU_CALLBACK,
	);
	$items['listado/ofertas'] = array(
	'title' => 'Todas las ofertas',
	'type' => MENU_DEFAULT_LOCAL_TASK,
	'weight' => 1,
	);
	$items['listado/ofertas_hechas'] = array(
		'title' => t('Listado de ofertas hechas'),
		'page callback' => 'forms_ofertas_listado_ofertas_usuario',
		'page arguments' => array('forms_ofertas_listado_ofertas_usuario'),
		'access callback' => 'user_access',
		'access arguments' => array('view offers'),
		'description' => t('Listado de ofertas hechas'),
		'type' => MENU_LOCAL_TASK,
		'weight' => 2,
	);
	$items['listado/suscripciones_usuario'] = array(
		'title' => t('Listado de suscripciones'),
		'page callback' => 'forms_ofertas_listado_suscripciones_usuario',
		'page arguments' => array('forms_ofertas_listado_suscripciones_usuario'),
		'access callback' => 'user_access',
		'access arguments' => array('view offers'),
		'description' => t('Listado de ofertas hechas'),
		'type' => MENU_LOCAL_TASK,
		'weight' => 3,
	);

return $items;
}
//Permisos a los elementos de menú
/**
* Implements hook_permission.
*/
function forms_forcontu_permission(){
	//dpm('hola');
	return array(
		'make an offer' => array(
		'title' => t('Access to offers module'),
		'description' => t('Access to offers module.'),
		),
		'view offers' => array(
		'title' => t('View offers made'),
		'description' => t('View offers made.'),
		),
		'update offers' => array(
		'title' => t('Update registered offers'),
		'description' => t('Update registered offers, only the owners.'),
		),
	);
}

/**
 * Implements hook_node_access().
 *
 * Allows view and edit access to private nodes, when the account requesting
 * access has the username 'foobar'.
 *
 * hook_node_access() was introduced in Drupal 7. We use it here to demonstrate
 * allowing certain privileges to an arbitrary user.
 *
 * @see hook_node_access()
 */
function forms_forcontu_node_access($node, $op, $account) {
 // If $node is a string, the node has not yet been created. We don't care
  // about that case.
	
	
	 $account = isset($account) ? $account : $GLOBALS['user'];
	 dpm($account);
  if (is_string($node)) {
    return NODE_ACCESS_DENY;
  }
  if (($op == 'view' || $op == 'update') && (!empty($account->name) && $account->name == 'foobar') && !empty($node->private)) {
    drupal_set_message(t('Access to node @nid allowed because requester name (@name) is specifically allowed', array('@name' => $node->name, '@uid' => $account->uid)));
    return NODE_ACCESS_ALLOW;
  }
  return NODE_ACCESS_ALLOW;
}

/**
 * Loads a user object.
 *
 * Drupal has a global $user object, which represents the currently-logged-in
 * user. So to avoid confusion and to avoid clobbering the global $user object,
 * it is a good idea to assign the result of this function to a different local
 * variable, generally $account. If you actually do want to act as the user you
 * are loading, it is essential to call drupal_save_session(FALSE); first.
 * See
 * @link http://drupal.org/node/218104 Safely impersonating another user @endlink
 * for more information.
 *
 * @param $uid
 *   Integer specifying the user ID to load.
 * @param $reset
 *   TRUE to reset the internal cache and load from the database; FALSE
 *   (default) to load from the internal cache, if set.
 *
 * @return
 *   A fully-loaded user object upon successful user load, or FALSE if the user
 *   cannot be loaded.
 *
 * @see user_load_multiple()
 */
function forms_forcontu_load($uid, $reset = FALSE) {
	alert('hola');
  $users = user_load_multiple(array($uid), array(), $reset);
  return reset($users);
}
/**
* Función de retorno para la página ofertas/formulario.
*/
function offers_form($form_state) {
$query = db_select('instruments', 'n');
	// Obtiene los datos de la base de datos (tabla node).
	$instruments = $query->
		fields('n',array('nid_instrument','name_instrument'))
		->condition('general_list', 1,'=')->execute();
	$options = array();
	$options[0] = 'Select an instrument';
	foreach ($instruments as $result) {
    	$options[$result->nid_instrument] = $result->name_instrument;
	}


	$form['description'] = array(
	'#type' => 'item',
	'#title' => t('Registra tu oferta'),
	);
	$form['to_play'] = array(
	'#type' => 'fieldset',
	'#title' => t('What do you want to play?'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);
	$form['to_play']['musical_piece'] = array(
	'#type' => 'textfield',
	'#title' => t('Musical piece'),
	'#required' => TRUE,
	'#default_value' => "",
	//'#description' => "Write the musical piece",
	'#size' => 75,
	'#maxlength' => 75,
	);
	$form['to_play']['author'] = array(
	'#type' => 'textfield',
	'#title' => t('Author'),
	'#required' => TRUE,
	'#default_value' => "",
	//'#description' => "Write the author",
	'#size' => 75,
	'#maxlength' => 75,
	);

//Músicos
	$form['performers'] = array(
	'#type' => 'fieldset',
	'#title' => t('How many performers do you need?'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);


	//botones
	$form['actions'] = array('#type' => 'actions');
	$form['actions']['submit'] = array(
	'#type' => 'submit',
	'#value' => t('Save'),
	);
	/*$form['actions']['cancel'] = array(
	'#type' => 'button',
	'#value' => t('Cancel'),
	);*/
	$form['actions']['cancel'] = array(
	'#markup' => l(t('Cancel'), ''),
	);

	$form['salon'] = array(
		'#type' => 'checkbox',
		'#title' => t('<strong>Do you need a rehearsal?</strong>'),
		//'#default_value' => array('red','green'),
		 //'#options' => array( '1' => t('Do you need a rehearsal?')),
		//'#options' => drupal_map_assoc(array('1' =>t('<strong>Do you need a rehearsal?</strong>'))),
	//),
	//'#description' => t('Select your preferences.'),
	);

	$form['piano'] = array(
		'#type' => 'checkbox',
		'#title' => t('<strong>Do you need piano?</strong>'),
		'#options' => array( '1' => t('<strong>Do you need piano?</strong>')),
		// Only show this field if persons is set to 'Other'.
	    '#states' => array(
	      'visible' => array(  // Action to take: Make visible.
	        ':input[name="salon"]' => array('checked' => TRUE),
	      ),
    ),

	//),
	//'#description' => t('Select if you need piano.'),
	);


	$form['city'] = array(
		'#type' => 'textfield',
		'#title' => t('City'),
		'#required' => TRUE,
		'#default_value' => "",
		//'#description' => "Write where do you want to play.",
		'#size' => 40,
		'#maxlength' => 40,
	);


	$form['time_availability'] = array(
		'#type' => 'textfield',
		'#title' => t('Time availability'),
		//'#default_value' => array('red','green'),
		//'#required' => TRUE,
		'#size' => 40,
		'#maxlength' => 40,
		
		//'#description' => t('Wich is your hour availability'),
		
	);
	
	// Construye el encabezado de la tabla (#header).
	$header = array(
	'name' => array('data' => t('Instrument'), 'field' => 'n.name_instrument'),
	'description' => array('data' => t('Description'), 'field' => 'n.description_instrument'),
	);

	
		
	//Construye el elemento de formulario select.
	$form['uid_usuario'] = array(
		'#type' => 'hidden',
		'#value' => $GLOBALS["user"]->uid,

	);
	

	$form['to_play']['autor_instrumet'] = array(
		'#type' => 'select',
		'#title' => t('Instrument to play by the author'),
		'#required' => TRUE,
		'#options' => $options,
            '#empty' => t('No content available.'),
	);		
 
    $no_of_fields = 4;     // The number of fields you wish to have in the form

    // Start adding the fields to the form
    for ($i=1; $i<=$no_of_fields; $i++)
    {
        $form['performers']['performers'.$i] = array(
            '#title' => t('Instrument no. '.$i),
            '#type' => 'select',
            '#options' => $options,
            '#empty' => t('No content available.'),
            
        ); 
        $form['performers']['other_permformers'.$i] = array(
		    '#type' => 'textfield',
		    '#size' => 50,
		    '#title' => t('Please enter the instrument.'),

		    // Only show this field if persons is set to 'Other'.
		    '#states' => array(
		      'visible' => array(  // Action to take: Make visible.
		        ':input[name="performers'.$i.'"]' => array('value' => '16'),
		      ),
		    ),
  		);

    }



 	$form['performers']['more_instruments'] = array(
    '#type' => 'checkbox',
    '#options' => drupal_map_assoc(array(t('More instrument/s'))),
    '#title' => t('More instruments'),
 	 );
  	/*$form['performers']['more_instruments'] = array(
    '#type' => 'textfield',
    '#size' => 75,
    '#title' => t('Please enter the instrument\'s name wich are needs separated by "|".'),

	    // Only show this field if persons is set to 'Other'.
	    '#states' => array(
	      'visible' => array(  // Action to take: Make visible.
	        ':input[name="persons[More instrument/s]"]' => array('checked' => TRUE),
	      ),
    ),
  );*/

	$form['performers']['more_performes'] = array(
	'#type' => 'fieldset',
	'#title' => t('How many performers do you need?'),
	'#collapsible' => TRUE,
	'#collapsed' => TRUE,
	    // Expand the expand_more_info fieldset if the box is checked.
    '#states' => array(
      'expanded' => array(
        ':input[name="more_instruments"]' => array('checked' => TRUE),
      ),
    ),
	);

	$no_of_fields = 9;     // The number of fields you wish to have in the form

    // Start adding the fields to the form
    for ($i=5; $i<=$no_of_fields; $i++)
    {
        $form['performers']['more_performes']['performers'.$i] = array(
            '#title' => t('Instrument no. '.$i),
            '#type' => 'select',
            '#options' => $options,
            '#empty' => t('No content available.'),
            
        ); 
        $form['performers']['more_performes']['other_permformers'.$i] = array(
		    '#type' => 'textfield',
		    '#size' => 50,
		    '#title' => t('Please enter the instrument.'),

		    // Only show this field if persons is set to 'Other'.
		    '#states' => array(
		      'visible' => array(  // Action to take: Make visible.
		        ':input[name="performers'.$i.'"]' => array('value' => '16'),
		      ),
		    ),
  		);

    }



return $form;
}


/**
* Función de envío del formulario offers_form
*/
function offers_form_submit($form, &$form_state){
	// Función de inserción de datos

	 $no_of_fields = 9;     // The number of fields you wish to have in the form
	 dpm($form_state);
 	$transaction = db_transaction();
 	 try {
			$id_oferta = db_insert('pym_ofertas')
				->fields(array(
					'uid' => $form_state['values']['uid_usuario'],
					'fecha_creacion' =>time(),
					'obra_musical' => $form_state['values']['musical_piece'],
					'autor_obra' => $form_state['values']['author'],
					'Salon' => $form_state['values']['rehearsal'],
					'Piano' => $form_state['values']['piano'],
					'Ciudad' => $form_state['values']['city'],
					'Disponibilidad' => $form_state['values']['time_availability'],
					//'Disponibilidad_tardes' => ($form_state['values']['time_availability'][2]==2) ? 1 : 0,
					//'Disponibilidad_finde' => ($form_state['values']['time_availability'][3]==3) ? 1 : 0,

					'Activo' => 1,
			
				))
				->execute();
				
				 $array_instruments = array();
			 	for ($i=1; $i<=$no_of_fields; $i++)
		    	{
			        if($form_state['values']['performers'.$i]!=0){
			        	$result = db_insert('pym_instrumentos_ofertas')
						->fields(array(
						'nid_instrument' => $form_state['values']['performers'.$i],
						'nid_oferta' => $id_oferta,
						'uid'=>0,
						'position'=>$i,
						))
						->execute();
							
			        }
		    
		    	}
				offers_form_mail_send($id_oferta,$form_state['values'],'new_offer');

				drupal_set_message ("<strong>Su oferta ha sido registrada correctamente.</strong> ");
		    }
		    catch (Exception $e) {
			   $transaction->rollback();
			    watchdog_exception('my_type', $e);
			    drupal_set_message ("<strong>Hubo un problema en el registro de su oferta, por favor inténtelo más tarde.</br>".$e->getMessage()."</strong> ");
			}
		
		drupal_goto("");
}


/* ENVIO DEL FORMULARIO AL USUARIO CREADOR DE LA OFERTA ****/

/**
 * Implement hook_mail().
 *
 * This hook defines a list of possible e-mail templates that this module can
 * send. Each e-mail is given a unique identifier, or 'key'.
 *
 * $message comes in with some standard properties already set: 'to' address,
 * 'from' address, and a set of default 'headers' from drupal_mail(). The goal
 * of hook_mail() is to set the message's 'subject' and 'body' properties, as
 * well as make any adjustments to the headers that are necessary.
 *
 * The $params argument is an array which can hold any additional data required
 * to build the mail subject and body; for example, user-entered form data, or
 * some context information as to where the mail request came from.
 *
 * Note that hook_mail() is not actually a hook. It is only called for a single
 * module, the module named in the first argument of drupal_mail(). So it's
 * a callback of a type, but not a hook.
 */
function forms_forcontu_mail($key, &$message, $params) {
  global $user;

  // Each message is associated with a language, which may or may not be the
  // current user's selected language, depending on the type of e-mail being
  // sent. This $options array is used later in the t() calls for subject
  // and body to ensure the proper translation takes effect.
  $options = array(
    'langcode' => $message['language']->language,
  );

  switch ($key) {
    // Se crea una nueva oferta
    case 'offer_owner':
      $message['subject'] = t('Registro de oferta enviado por @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
      // Note that the message body is an array, not a string.
      $message['body'][] = t('@name Le envía a usted un mensaje de confirmación del alta de su oferta:', array('@name' => variable_get('site_name', 'Drupal')), $options);
      // Because this is just user-entered text, we do not need to translate it.

      // Since user-entered text may have unintentional HTML entities in it like
      // '<' or '>', we need to make sure these entities are properly escaped,
      // as the body will later be transformed from HTML to text, meaning
      // that a normal use of '<' will result in truncation of the message.
      $message['body'][] = check_plain($params['message']);
      break;
    case 'admin_mail':
		      $message['subject'] = t('Registro de oferta enviado por @user-name', array('@user-name' => $user->name), $options);
		      // Note that the message body is an array, not a string.
		      $message['body'][] = t('Se acaba de crear una nueva oferta con los siguientes datos:', $options);
		      // Because this is just user-entered text, we do not need to translate it.

		      // Since user-entered text may have unintentional HTML entities in it like
		      // '<' or '>', we need to make sure these entities are properly escaped,
		      // as the body will later be transformed from HTML to text, meaning
		      // that a normal use of '<' will result in truncation of the message.
		      $message['body'][] = check_plain($params['message']);
		      break;

	//Se realiza una suscripción	      
     case 'offer_subscriber':
		     $message['subject'] = t('Registro de suscripción enviado por @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
		      // Note that the message body is an array, not a string.
		      $message['body'][] = t('@name Le envía a usted un mensaje de confirmación del alta de su suscripción a la oferta:', array('@name' => variable_get('site_name', 'Drupal')), $options);
		      // Because this is just user-entered text, we do not need to translate it.

		      // Since user-entered text may have unintentional HTML entities in it like
		      // '<' or '>', we need to make sure these entities are properly escaped,
		      // as the body will later be transformed from HTML to text, meaning
		      // that a normal use of '<' will result in truncation of the message.
		      $message['body'][] = check_plain($params['message']);
		      break;
     break;

     case 'subscriber_offer_owner':
	      $message['subject'] = t('Registro de suscripción enviado por @user-name', array('@user-name' => $user->name), $options);
	      // Note that the message body is an array, not a string.
	      $message['body'][] = t('@user-name Se acaba de suscribir a una de tus ofertas con los siguientes datos:',array('@user-name' => $user->name), $options);
	      // Because this is just user-entered text, we do not need to translate it.

	      // Since user-entered text may have unintentional HTML entities in it like
	      // '<' or '>', we need to make sure these entities are properly escaped,
	      // as the body will later be transformed from HTML to text, meaning
	      // that a normal use of '<' will result in truncation of the message.
	      $message['body'][] = check_plain($params['message']);
     break;


     //Se finaliza una oferta      
     case 'closed_offer_owner':
		     $message['subject'] = t('Registro de cierre de oferta enviado por @site-name', array('@site-name' => variable_get('site_name', 'Drupal')), $options);
		      // Note that the message body is an array, not a string.
		      $message['body'][] = t('@name Le comunica que una de sus ofertas se ha cerrado con éxito, los de detalles de la misma a continuación:', array('@name' => variable_get('site_name', 'Drupal')), $options);
		      // Because this is just user-entered text, we do not need to translate it.

		      // Since user-entered text may have unintentional HTML entities in it like
		      // '<' or '>', we need to make sure these entities are properly escaped,
		      // as the body will later be transformed from HTML to text, meaning
		      // that a normal use of '<' will result in truncation of the message.
		      $message['body'][] = check_plain($params['message']);
     break;

     case 'closed_offer_admin_mail':
	      $message['subject'] = t('Registro de cierre de oferta de @user-name', array('@user-name' => $user->name), $options);
	      // Note that the message body is an array, not a string.
	      $message['body'][] = t('Se acaba de cerrar con éxito la siguiente oferta:', $options);
	      // Because this is just user-entered text, we do not need to translate it.

	      // Since user-entered text may have unintentional HTML entities in it like
	      // '<' or '>', we need to make sure these entities are properly escaped,
	      // as the body will later be transformed from HTML to text, meaning
	      // that a normal use of '<' will result in truncation of the message.
	      $message['body'][] = check_plain($params['message']);
     break;
  }
}


/**
 * Sends an e-mail.
 *
 * @param $form_values
 *   An array of values from the contact form fields that were submitted.
 *   There are just two relevant items: $form_values['email'] and
 *   $form_values['message'].
 */
function offers_form_mail_send($id_oferta, $form_values, $operation) {
	global $user;
	global $language, $base_url;
 
 

  	// Email de administración del sitio
	$site_mail = variable_get('site_mail');
	// Email del usuario (indicado en el formulario)
	$user_mail = $user->init;
										
	$form_url = $base_url . '/?q=ofertas/'.$id_oferta.'/user/'.$user->uid.'/detalle/view';

  // Specify 'to' and 'from' addresses.
  $to = $user->init;
  $from = variable_get('site_mail', 'ariel.card@gmail.com');

  // "params" loads in additional context for email content completion in
  // hook_mail(). In this case, we want to pass in the values the user entered
  // into the form, which include the message body in $form_values['message'].
  //$params = $form_values;


  	$params = array();
	$params['subject'] = t('[@site_name] : Alert from offer create', array( '@site_name' => variable_get('site_name', 'Drupal'),
	));
	$params['message'] = "\nNombre Autor:".$form_values['author'];
	$params['message'] .= "\nObra: ".$form_values['musical_piece'];
	$params['message'] .= "\nCiudad: ".$form_values['city'];
	$params['message'] .= "\nEnlace: ".$form_url;

  // The language of the e-mail. This will one of three values:
  // * user_preferred_language(): Used for sending mail to a particular website
  //   user, so that the mail appears in their preferred language.
  // * global $language: Used when sending a mail back to the user currently
  //   viewing the site. This will send it in the language they're currently
  //   using.
  // * language_default(): Used when sending mail to a pre-existing, 'neutral'
  //   address, such as the system e-mail address, or when you're unsure of the
  //   language preferences of the intended recipient.
  //
  // Since in our case, we are sending a message to a random e-mail address that
  // is not necessarily tied to a user account, we will use the site's default
  // language.
  $language = language_default();

  // Whether or not to automatically send the mail when drupal_mail() is
  // called. This defaults to TRUE, and is normally what you want unless you
  // need to do additional processing before drupal_mail_send() is called.
  $send = TRUE;
  // Send the mail, and check for success. Note that this does not guarantee
  // message delivery; only that there were no PHP-related issues encountered
  // while sending.


 // All system mails need to specify the module and template key (mirrored from
  // hook_mail()) that the message they want to send comes from.
  $module = 'forms_forcontu';
  $key = '';
  $key_admin = '';
  if($operation == 'new_offer'){
 		$key = 'offer_owner';
  		$key_admin = 'admin_mail';
  }
  if($operation == 'subscription'){
  		$key = 'offer_subscriber'; //suscriptor de la oferta
  		$key_admin = 'subscriber_offer_owner'; //propietario de la oferta a la que se han suscrito
  		$site_mail =  $form_values['mail'];
  }
  if($operation == 'close_offer'){
		$key = 'closed_offer_owner';
  		$key_admin = 'closed_offer_admin_mail';
  		$to =  $form_values['mail'];
  }

  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
  if ($result['result'] == TRUE ) {
	if( $operation != 'close_offer'){
 		drupal_set_message(t('Your message has been sent.'));
	}
  
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }

  drupal_mail($module, $key_admin, $site_mail, $language, $params, $from, $send);

}

/**
 * Implement hook_mail_alter().
 *
 * This function is not required to send an email using Drupal's mail system.
 *
 * Hook_mail_alter() provides an interface to alter any aspect of email sent by
 * Drupal. You can use this hook to add a common site footer to all outgoing
 * email, add extra header fields, and/or modify the email in anyway. HTML-izing
 * the outgoing email is one possibility.
 */
function forms_forcontu_mail_alter(&$message) {

  $options = array(
    'langcode' => $message['language']->language,
  );

  $signature = t("\n--\nCorreo enviado por el equipo de Piano y Mengano.", array(), $options);
  if (is_array($message['body'])) {
    $message['body'][] = $signature;
  }
  else {  // Some modules use the body as a string, erroneously.
    $message['body'] .= $signature;
  }
}

function forms_ofertas_detalle_edit($form, &$form_state, $account, $category = 'account') {
//function forms_ofertas_detalle_edit($form,&$form_state) {
	  global $user;


  // During initial form build, add the entity to the form state for use during
  // form building and processing. During a rebuild, use what is in the form
  // state.
  if (!isset($form_state['user'])) {
    $form_state['user'] = $account;
  }
  else {
    $account = $form_state['user'];
  }

  // @todo Legacy support. Modules are encouraged to access the entity using
  //   $form_state. Remove in Drupal 8.
  $form['#user'] = $account;
  $form['#user_category'] = $category;


 	$operacion = '';

	$id = $form_state['build_info']['args'][0];
		
	global $user;
	$form['nid_oferta'] = array(
		'#type' => 'hidden',
		'#title' => t('Oferta'),
		'#value' => $id,
	);


	$oferta = db_select('pym_ofertas', 'n')
		->fields('n', array('fecha_creacion', 'uid','obra_musical', 'autor_obra','Salon','Piano','Ciudad','Disponibilidad_manana','Disponibilidad_tardes',
							'Disponibilidad_finde'))
		->condition('nid_oferta', $id,'=')
		->condition('Activo', 1,'=');
		
	
	$oferta->addField('u', 'name','name');
	$oferta->leftJoin('users', 'u', 'u.uid = n.uid ');

	$record = $oferta->execute()->fetchObject();
	/*$autor_oferta = db_select('users', 'n')
		->fields('n', array('name'))
		->condition('uid', $record->uid,'=')
		->execute();*/

	//$autor_of = $autor_oferta->fetchObject();	
	//opciones que estarán checkeadas a TRUE
	$options_checked = array('11','21','31');

	$form['personal_data'] = array(
	'#type' => 'fieldset',
	'#title' => t('Datos de la oferta. Author: <strong> '.$record->name.'</strong>'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);
	$form['personal_data']['obra_musical'] = array(
		'#type' => 'textfield',
		'#title' => t('Obra a tocar'),
		'#default_value' => $record->obra_musical,
		'#required' => TRUE,
	);
	$form['personal_data']['autor_obra'] = array(
		'#type' => 'textfield',
		'#title' => t('Autor de la Obra'),
		'#default_value' => $record->autor_obra,
		'#required' => TRUE,
	);
	$form['personal_data']['Salom'] = array(
		'#type' => 'checkbox',
		'#title' => t('Se necesita Salon'),
		'#default_value' => ($record->Salon==0)?0:1,
	);
	$form['personal_data']['Piano'] = array(
		'#type' => 'checkbox',
		'#title' => t('Se necesita Piano'),
		'#default_value' => ($record->Piano==0)?0:1,
	);
	$form['personal_data']['Ciudad'] = array(
		'#type' => 'textfield',
		'#title' => t('City to play'),
		'#default_value' => $record->Ciudad,
		'#required' => TRUE,
	);
	$form['personal_data']['Disponibilidad'] = array(
		'#type' => 'textfield',
		'#title'=> t('Availability'),
		'#default_value' => $record->Disponibilidad,
		//'#collapsed' => FALSE,
	);

		
		/*$options = array('1'.$record->Disponibilidad_tardes =>'Afternoon availability', 
						 '2'.$record->Disponibilidad_manana =>'Morning availability',
						 '3'.$record->Disponibilidad_finde =>'Weekend availability',
						);
		
		$form['personal_data']['Disponibilidad']['availability'] = array(
		'#type' => 'checkboxes',
		'#title' => t(''),
		'#options' => $options,
		'#default_value' => $options_checked,// $options_checked is an array similar to $options but having elements which need to be checked by default...
		);*/


	$form['instruments']= array(
		'#type' => 'fieldset',
		'#title'=> t('Instruments'),
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
		'#description' => t('Select the instrument wich you want to suscribe to.'),
	);

	
	$header = array(
	'Instrumento' => array('data' => t('Instrumento'), 'field' => 'i.name_instrument'),
	'Suscriptor' => array('data' => t('Suscriptor'), 'field' => 'u.name'),
	'Activo' => array('data' => t('Estado'), 'field' => 'io.position'),
	
	);
	$instrumentos = db_select('pym_instrumentos_ofertas', 'io')
			->fields('io', array('nid_oferta', 'nid_instrument', 'uid','position'))
			->condition('nid_oferta', $id,'=');
			//->condition('activo', 1,'=');
	$instrumentos->addField('u', 'name', 'name');
	$instrumentos->addField('i', 'name_instrument', 'name_instrument');
	$instrumentos->leftJoin('users', 'u', 'io.uid = u.uid ');
	$instrumentos->leftJoin('instruments', 'i', 'io.nid_instrument = i.nid_instrument ');
	//defino una línea de instrumento 
  	$entries = $instrumentos->execute()->fetchAll();

	//Instrumentos seleccionados por el usuario actual
	$instrumentos_usuario = db_select('pym_instrumentos_ofertas', 'io')
			//->fields('io', array('uid'))
			->condition('nid_oferta', $id,'=')
			->condition('uid', $user->uid,'=');

	$instrumentos_usuario->addExpression('COUNT(uid)', 'uid_count');
	
	$ii = $instrumentos_usuario->execute()->fetchObject();
	//Se activa con la primera aparición del nombre en la lista de suscriptos
	if($ii->uid_count>0) {
		$booleanSuscripcion = TRUE;
		drupal_set_message('You are already subscribed to this offer. You havent got permission to select another one');
	}
	else
	{
		$booleanSuscripcion = FALSE;
	}



	$options = array();
	$optout = array();

	
	    foreach ($entries as $entry) {
	      $key = $entry->nid_instrument.'-'.$entry->nid_oferta.$entry->position;
        
	      if(evaluaCondiciones($entry,$user,$record) || $booleanSuscripcion)$optout[$key] = TRUE;
	      $options[$key] = array(

						'Instrumento' => check_plain($entry->name_instrument),
						'Suscriptor' => array(
									'data' => array(
									'#type' => 'link',
									'#title' => $entry->name,
									'#href' => 'user/' . $entry->uid,
									),
						),
						'Activo' => (empty($entry->name))?'Si':'No',
						);
	    }
	 

	$form['instruments']['instruments'] = array(
		'#type' => 'tableselect',
		'#header' => $header,
		'#options' => $options,
		'#empty' => t('No tiene contenido.'),
		'#multiple' => FALSE,
		'#required' => TRUE,
	);

	foreach( $optout as $key => $value )
	{
	  $form['instruments']['instruments'][$key]['#disabled'] = true;
	}
 	


 	//if(empty($optout)){
	 	//botones
		$form['actions'] = array('#type' => 'actions');
		$form['actions']['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Update'),
			//'#attributes' => array('onclick' => 'if(!confirm("Really want to subscribe?")){return false;}')
		);
	//}

  	$form['#multistep'] = TRUE;
  	$form['#action'] = url('ofertas/ver/detalle/confirm');
  	return $form;

}
/*  DETALLE DE LA OFERTA */
function forms_ofertas_detalle($form,&$form_state) {
	//dpm($form_state);
	$operacion = '';

	$id = $form_state['build_info']['args'][0];
		
	global $user;
	$form['nid_oferta'] = array(
		'#type' => 'hidden',
		'#title' => t('Oferta'),
		'#value' => $id,
	);


	$oferta = db_select('pym_ofertas', 'n')
		->fields('n', array('fecha_creacion', 'uid','obra_musical', 'autor_obra','Salon','Piano','Ciudad','Disponibilidad_manana','Disponibilidad_tardes',
							'Disponibilidad_finde'))
		->condition('nid_oferta', $id,'=')
		->condition('Activo', 1,'=');
		
	
	$oferta->addField('u', 'name','name');

	$oferta->addField('u', 'mail','mail');

	$oferta->leftJoin('users', 'u', 'u.uid = n.uid ');

	$record = $oferta->execute()->fetchObject();
	/*$autor_oferta = db_select('users', 'n')
		->fields('n', array('name'))
		->condition('uid', $record->uid,'=')
		->execute();*/

	//$autor_of = $autor_oferta->fetchObject();	
	//opciones que estarán checkeadas a TRUE
	$options_checked = array('11','21','31');

	$form['personal_data'] = array(
	'#type' => 'fieldset',
	'#title' => t('Datos de la oferta.'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);
	$form['personal_data']['mail'] = array(
		'#type' => 'hidden',
		'#default_value' => $record->mail,
	);
	$form['personal_data']['autor_oferta'] = array(
		'#type' => 'item',
		'#title' => t('Autor de la oferta'),
		'#markup' => t('!url', array('!url' => l(t($record->name), "user/$record->uid"))),
	);
	$form['personal_data']['obra_musical'] = array(
		'#type' => 'item',
		'#title' => t('Obra a tocar'),
		'#markup' => $record->obra_musical,
	);
	$form['personal_data']['musical_piece'] = array(
		'#type' => 'hidden',
		'#default_value' => $record->obra_musical,
	);
	$form['personal_data']['autor_obra'] = array(
		'#type' => 'item',
		'#title' => t('Autor de la Obra'),
		'#markup' => $record->autor_obra,
	);
	$form['personal_data']['author'] = array(
		'#type' => 'hidden',
		'#default_value' => $record->autor_obra,
	);
	$form['personal_data']['Salon'] = array(
		'#type' => 'item',
		'#title' => t('Se necesita Salon'),
		'#markup' => ($record->Salon==0)?'No':'Si',
	);
	$form['personal_data']['Piano'] = array(
		'#type' => 'item',
		'#title' => t('Se necesita Piano'),
		'#markup' => ($record->Piano==0)?'No':'Si',
	);
	$form['personal_data']['Ciudad'] = array(
		'#type' => 'item',
		'#title' => t('City to play'),
		'#markup' => ($record->Ciudad),

	);
	$form['personal_data']['city'] = array(
		'#type' => 'hidden',
		'#default_value' => $record->Ciudad,

	);
	$form['personal_data']['Disponibilidad'] = array(
		'#type' => 'item',
		'#title'=> t('Availability'),
		'#markup' => ($record->Disponibilidad),
		
	);

		
		/*$options = array('1'.$record->Disponibilidad_tardes =>'Afternoon availability', 
						 '2'.$record->Disponibilidad_manana =>'Morning availability',
						 '3'.$record->Disponibilidad_finde =>'Weekend availability',
						);
		
		$form['personal_data']['Disponibilidad']['availability'] = array(
		'#type' => 'checkboxes',
		'#title' => t(''),
		'#options' => $options,
		'#default_value' => $options_checked,// $options_checked is an array similar to $options but having elements which need to be checked by default...
		'#disabled' => TRUE,
		);*/
		




	$form['instruments']= array(
		'#type' => 'fieldset',
		'#title'=> t('Instruments'),
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
		'#description' => t('Select the instrument wich you want to suscribe to.'),
	);

	
	$header = array(
	'Instrumento' => array('data' => t('Instrumento'), 'field' => 'i.name_instrument'),
	'Suscriptor' => array('data' => t('Suscriptor'), 'field' => 'u.name'),
	'Activo' => array('data' => t('Activo'), 'field' => 'io.position'),
	
	);
	$instrumentos = db_select('pym_instrumentos_ofertas', 'io')
			->fields('io', array('nid_oferta', 'nid_instrument', 'uid','position'))
			->condition('nid_oferta', $id,'=');
			//->condition('activo', 1,'=');
	$instrumentos->addField('u', 'name', 'name');
	$instrumentos->addField('i', 'name_instrument', 'name_instrument');
	$instrumentos->leftJoin('users', 'u', 'io.uid = u.uid ');
	$instrumentos->leftJoin('instruments', 'i', 'io.nid_instrument = i.nid_instrument ');
	//defino una línea de instrumento 
  	$entries = $instrumentos->execute()->fetchAll();

	//Instrumentos seleccionados por el usuario actual
	$instrumentos_usuario = db_select('pym_instrumentos_ofertas', 'io')
			//->fields('io', array('uid'))
			->condition('nid_oferta', $id,'=')
			->condition('uid', $user->uid,'=');

	$instrumentos_usuario->addExpression('COUNT(uid)', 'uid_count');
	
	$ii = $instrumentos_usuario->execute()->fetchObject();
	//Se activa con la primera aparición del nombre en la lista de suscriptos
	if($ii->uid_count>0) {
		$booleanSuscripcion = TRUE;
		drupal_set_message('You are already subscribed to this offer. You havent got permission to select another one');
	}
	else
	{
		$booleanSuscripcion = FALSE;
	}

	$options = array();
	$optout = array();

	
	    foreach ($entries as $entry) {
	      $key = $entry->nid_instrument.'-'.$entry->nid_oferta.$entry->position;
        
	      if(evaluaCondiciones($entry,$user,$record) || $booleanSuscripcion)$optout[$key] = TRUE;
	      $options[$key] = array(

						'Instrumento' => check_plain($entry->name_instrument),
						'Suscriptor' => array(
									'data' => array(
									'#type' => 'link',
									'#title' => $entry->name,
									'#href' => 'user/' . $entry->uid,
									),
						),
						'Activo' => (empty($entry->name))?'Si':'No',
						);
	    }
	 

	$form['instruments']['instruments'] = array(
		'#type' => 'tableselect',
		'#header' => $header,
		'#options' => $options,
		'#empty' => t('No tiene contenido.'),
		'#multiple' => FALSE,
		'#required' => TRUE,
	);

	foreach( $optout as $key => $value )
	{
	  $form['instruments']['instruments'][$key]['#disabled'] = true;
	}
 	


//drupal_set_message($optout[0]);
 	//if(empty($optout)){

	 	//botones
		$form['actions'] = array('#type' => 'actions');
		$form['actions']['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Continue'),
			//'#attributes' => array('onclick' => 'if(!confirm("Really want to subscribe?")){return false;}')
		);

	//}


  	$form['#multistep'] = TRUE;
  	$form['#action'] = url('ofertas/ver/detalle/confirm');
  	return $form;

}

function evaluaCondiciones($entry,$user,$record){
	if (!empty($entry->name))return true;

	if ($record->uid == $user->uid) return true;


	//if($user->name == )
	return false;
}

/**
* Función de validación del formulario forms_ofertas_detalle
*/
/**
* Implements hook_validate().
*/
function forms_ofertas_detalle_validate($form, &$form_state){

dpm($form_state);
form_set_error('lista', t('You must enter a valid e-mail address.'));
/*if (!valid_email_address($form_state['values']['email'])) {
	
}*/
}


function forms_ofertas_detalle_submit($form, &$form_state) {
	drupal_set_message(t('Verify submission.'));
}

function forms_ofertas_detalle_confirm(){
	// Get the post values (what user entered)
  $edit = $_POST;

	//drupal_set_message($_POST['mail']);	


  $form = array();
   $num = preg_split("/\/|-/",$edit['instruments']);


$form['author'] = array(
    '#type' => 'hidden',
    '#title' => t('autor'),
    '#value' => $edit['author']
  );
  $form['musical_piece'] = array(
    '#type' => 'hidden',
    '#title' => t('obra'),
    '#value' => $edit['musical_piece']
  );
  $form['city'] = array(
    '#type' => 'hidden',
    '#title' => t('ciudad'),
    '#value' => $edit['city'] 
  );
   $form['mail'] = array(
    '#type' => 'hidden',
    '#title' => t('correo'),
    '#value' => $edit['mail'] 
  );
   



  $form['instruments'] = 
  $form['instruments'] = array(
    '#type' => 'hidden',
    '#title' => t('Instruments'),
    '#value' => $num[0] // Include the $_POST form values
  );

	$form['nid_oferta'] = array(
    '#type' => 'hidden',
    '#title' => t('Instruments'),
    '#value' => $edit['nid_oferta'] // Include the $_POST form values
  	);

  $form= confirm_form($form,
	    t('Do you want to subscribe to this offer?'), '/',
	    t('Only do this if you are sure!'),
	    t('Subscribe to it!'),
	    t('Nevermind')
  );

  return $form;
}


//Se envía la suscripción a una oferta
function forms_ofertas_detalle_confirm_submit($form, &$form_state) {
	global $user; 
	$transaction = db_transaction();
	try{
		db_update('pym_instrumentos_ofertas')

				->fields(array( 'uid'=>$user->uid,))
				->condition('nid_oferta', $form_state['values']['nid_oferta'],'=')
				->condition('nid_instrument', $form_state['values']['instruments'],'=')
				->execute();
		
		offers_form_mail_send($form_state['values']['nid_oferta'], $form_state['values'], 'subscription');

		//Comprobamos si la oferta está completa
		if(is_complete($form_state['values']['nid_oferta'])){
			db_update('pym_ofertas')
				->fields(array( 'activo'=>0,))
				->condition('nid_oferta', $form_state['values']['nid_oferta'],'=')
				->execute();
		}
		//mails de cierre de oferta
		offers_form_mail_send($form_state['values']['nid_oferta'], $form_state['values'], 'close_offer');
		drupal_set_message('You have successfully subscribed.');
		drupal_goto("");
	}
	catch (PDOException $e) {
		$transaction->rollback();
      	watchdog_exception('user', $e);
  		drupal_set_message(t('Error: %message', array('%message' => $e->getMessage())), 'error');
  		 drupal_goto("");
	}
	 



}

//comprobamos si es la ultima suscripción para esa oferta
function is_complete($id){

		
	$instrumentos_usuario = db_select('pym_instrumentos_ofertas', 'io')
			//->fields('io', array('uid'))
			->condition('nid_oferta', $id,'=')
			->condition('uid', 0,'=');

	$instrumentos_usuario->addExpression('COUNT(nid_oferta)', 'nid_oferta');
	
	$ii = $instrumentos_usuario->execute()->fetchObject();
	//Se activa con la primera aparición del nombre en la lista de suscriptos
	if($ii->nid_oferta>0) {
		return false;
	}
	return true;
}

/**
* Se expone el listado de ofertas realizadas por el usuario
*
*/
function forms_ofertas_listado_ofertas_usuario($form_state) {
	global $user;

	$id = $user->uid;
	$output = '';
	$header = array(
		'created' => array('data' => t('Creado'), 'field' => 'fecha_creacion','sort' => 'asc'),
		'Music piece' => array('data' => t('Music piece'), 'field' => 'obra_musical'),
		'Author Obra' => array('data' => t('Author'), 'field' => 'name'),
		'Ciudad' => array('data' => t('City'), 'field' => 'ciudad'),
		'Activo' => array('data' => t('Estado'), 'field' => 'activo','sort' => 'asc'),
	);

	$query = db_select('pym_ofertas', 'pym');
	//$query->range(0, 10);
	// Obtiene los datos de la base de datos (tabla node).
	$query->fields('pym',array('nid_oferta','fecha_creacion','autor_obra','obra_musical','ciudad','activo'))
				->condition('u.uid', $id,'=');
	$query->join('users', 'u', 'u.uid = pym.uid');
	      
	
	//$query->addField('u', 'name');
	//$query->addField('u', 'uid');
	//$query->leftJoin('users', 'u', 'u.uid = pym.uid');
	$query = $query->extend('PagerDefault')->limit(20); // line1
	$query = $query->extend('TableSort');
	$offers = $query->orderByHeader($header)->execute()->fetchAll();
	$options = array();




  if (!empty($offers)) {
    $rows = array();
    foreach ($offers as $entry) {
      // Sanitize the data before handing it off to the theme layer.

    	$row = array(
			'created' => date('d-M-Y', $entry->fecha_creacion),
			'Music piece' => array(
							'data' => array(
										'#type' => 'link',
										'#title' => $entry->obra_musical,
										'#href' => 'ofertas/'.$entry->nid_oferta.'/user/'.$id.'/detalle/view' ,
										'#options' => $options,
										),
									),
			
			
			'Author Oferta' => $entry->autor_obra,
			'Ciudad' => $entry->ciudad,
			//'Estado' => $entry->activo,
			'Estado' => (empty($entry->activo))?'cerrada':'abierta',

		);
      $rows[] = $row;
    }
    // Make a table for them.
    //$header = array(t('created'), t('Music piece'), t('Offer Author'),t('Estado'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
     $output .= theme('pager');
  }
  else {
    drupal_set_message(t('No se han encontrado ofertas realizadas'));
  }

return $output;
}


/**
* Listado de suscripciones del usuario
*
*
*/
function forms_ofertas_listado_suscripciones_usuario($form_state) {
	global $user;
	$id = $user->uid;
	$output = '';
	$header = array(
		'created' => array('data' => t('Creado'), 'field' => 'fecha_creacion','sort' => 'asc'),
		'Music piece' => array('data' => t('Music piece'), 'field' => 'obra_musical'),
		'Author Obra' => array('data' => t('Offer Author'), 'field' => 'name'),
		'Ciudad' => array('data' => t('City'), 'field' => 'ciudad'),
		'Activo' => array('data' => t('Estado'), 'field' => 'activo','sort' => 'asc'),
	);

	$suscripciones = db_select('pym_instrumentos_ofertas', 'pym_io');
	$suscripciones->fields('pym',array('nid_oferta', 'uid'))
					->condition('pym_io.uid', $id,'=');
    $suscripciones->addField('pym', 'nid_oferta');
    $suscripciones->addField('pym', 'fecha_creacion');
    $suscripciones->addField('pym', 'autor_obra');
    $suscripciones->addField('pym', 'obra_musical');
    $suscripciones->addField('pym', 'ciudad');
    $suscripciones->addField('pym', 'activo');
	$suscripciones->leftJoin('pym_ofertas', 'pym', 'pym_io.nid_oferta = pym.nid_oferta');


	$suscripciones = $suscripciones->extend('PagerDefault')->limit(20); // line1
	$suscripciones = $suscripciones->extend('TableSort');
	$offers = $suscripciones->orderByHeader($header)->execute()->fetchAll();
	$options = array();

/*
	$query = db_select('pym_ofertas', 'pym');
	//$query->range(0, 10);
	// Obtiene los datos de la base de datos (tabla node).
	$query->fields('pym',array('nid_oferta','fecha_creacion','autor_obra','obra_musical','activo'))
	//$query->join('users', 'u', 'u.uid = pym.uid');
	->condition('uid', $id,'=');
	
	//$query->addField('u', 'name');
	//$query->addField('u', 'uid');
	//$query->leftJoin('users', 'u', 'u.uid = pym.uid');
	$query = $query->extend('PagerDefault')->limit(20); // line1
	$query = $query->extend('TableSort');
	$offers = $query->orderByHeader($header)->execute()->fetchAll();
	$options = array();
*/



  if (!empty($offers)) {
    $rows = array();
    foreach ($offers as $entry) {
      // Sanitize the data before handing it off to the theme layer.

    	$row = array(
			'created' => date('d-M-Y', $entry->fecha_creacion),
			'Music piece' => array(
							'data' => array(
										'#type' => 'link',
										'#title' => $entry->obra_musical,
										
										'#href' => 'ofertas/'.$entry->nid_oferta.'/user/'.$id.'/detalle/view' ,
										'#options' => $options,
										),
									),
			
			
			'Author Oferta' => $entry->autor_obra,
			'Ciudad' => $entry->ciudad,
			//'Estado' => $entry->activo,
			'Estado' => (empty($entry->activo))?'cerrada':'abierta',

		);
      $rows[] = $row;
    }
    // Make a table for them.
    //$header = array(t('created'), t('Music piece'), t('Offer Author'),t('Estado'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
     $output .= theme('pager');
  }
  else {
    drupal_set_message(t('No se han encontrado ofertas'));
  }

return $output;
}
/**
* Función de retorno para la página de listado de ofertas.
*/
function forms_ofertas_listado($form_state) {
	
 	$output = '';
	$header = array(
	'created' => array('data' => t('Creado'), 'field' => 'fecha_creacion','sort' => 'asc'),
	'Music piece' => array('data' => t('Music piece'), 'field' => 'obra_musical'),
	'Author Oferta' => array('data' => t('Author Oferta'), 'field' => 'name'),
	'Ciudad' => array('data' => t('City'), 'field' => 'ciudad'),

	'Activo' => array('data' => t('Estado'), 'field' => 'activo','sort' => 'asc'),
	);

	$query = db_select('pym_ofertas', 'pym');
	//$query->range(0, 10);
	// Obtiene los datos de la base de datos (tabla node).
	$query->fields('pym',array('nid_oferta','fecha_creacion','autor_obra','obra_musical','ciudad','activo'));
	//$query->join('users', 'u', 'u.uid = pym.uid');
	$query->addField('u', 'name');
	$query->addField('u', 'uid');
	$query->leftJoin('users', 'u', 'u.uid = pym.uid');
	$query = $query->extend('PagerDefault')->limit(20); // line1
	$query = $query->extend('TableSort');
	$offers = $query->orderByHeader($header)->execute()->fetchAll();
	$options = array();




  if (!empty($offers)) {
    $rows = array();
    foreach ($offers as $entry) {
 
    	$row = array(
			'created' => date('d-M-Y', $entry->fecha_creacion),
			'Music piece' => array(
							'data' => array(
										'#type' => 'link',
										'#title' => $entry->obra_musical,
										
										'#href' => 'ofertas/'.$entry->nid_oferta.'/user/'.$entry->uid.'/detalle/view' ,
										'#options' => $options,
										),
									),
			
			'Author Oferta' => array(
							'data' => array(
										'#type' => 'link',
										'#title' => $entry->name,
										'#href' => 'user/' . $entry->uid,
										'#options' => $options,
										),
									),
			//'Author Oferta' => $entry->name,
			//'Estado' => $entry->activo,
			'Ciudad' => $entry->ciudad,
			'Estado' => (empty($entry->activo))?'cerrada':'abierta',

		);
      $rows[] = $row;
    }
    // Make a table for them.
    //$header = array(t('created'), t('Music piece'), t('Offer Author'),t('Estado'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
     $output .= theme('pager');
  }
  else {
    drupal_set_message(t('No se han encontrado ofertas'));
  }

return $output;
}
/**
 * Implements hook_help().
 *
 * Show a bit of information about this module on the example page
 */
function forms_forcontu_help($path, $arg) {
global $user;
  switch ($path) {
    case 'ofertas/listado':
      return '<p>' . t('Offers list You can click on each one to acces to its details .') . '</p>';
     case 'formulario/oferta':
      return '<p>' . t('Se podrán ver las ofertas realizadas por usted. Los campos con asteriscos (*) son obligatorios .') . '</p>';
  }
}

/*function forms_forcontu_menu_alter(&$items) {
  $items['ofertas/%/detalle/edit']['access callback'] = 'ofertas_user_edit_access';
}*/
/**
* Access callback for user account editing.
 *
 */
function ofertas_user_edit_access($account) {
	//drupal_set_message(t($account->uid));

	//dpm($GLOBALS['user']);
	drupal_set_message(t($GLOBALS['user']->uid));
	return TRUE;
	
  //return ((($GLOBALS['user']->uid == $user->uid) && user_access('update offers')) || user_access('administer users')) && $user->uid > 0;
}