<?php

global $user;
/**
* @file
* Menu Forcontu
* Forcontu - Ejemplos de formulario
*/


/**
* Implements hook_menu().
*/
function gestion_ofertas_menu() {
	$items['ofertas/listado'] = array(
	'title' => t('Listado de ofertas'),
	'page callback' => 'drupal_get_form',
	'page arguments' => array('forms_ofertas_listado'),
	'access callback' => TRUE,
	'description' => t('Example Form 1'),
	'type' => MENU_CALLBACK,

	);

	$items['ofertas/ver/integrantes'] = array(
	'title' => t('Listado de ofertas'),
	'page callback' => 'drupal_get_form',
	'page arguments' => array('forms_ofertas_integrantes'),
	'access callback' => TRUE,
	'description' => t('Example Form 1'),
	'type' => MENU_CALLBACK,

	);

return $items;
}

function forms_ofertas_integrantes($form_state) {
	return $form;
}
/**
* Función de retorno para la página forms_forcontu/form1.
*/
function forms_ofertas_listado($form_state) {
	$form['description'] = array(
	'#type' => 'item',
	'#title' => t('Registra tu oferta'),
	);
	$form['to_play'] = array(
	'#type' => 'fieldset',
	'#title' => t('What do you want to play?'),
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);
	$form['to_play']['musical_piece'] = array(
	'#type' => 'textfield',
	'#title' => t('Musical piece'),
	'#required' => TRUE,
	'#default_value' => "",
	'#description' => "Write the musical piece",
	'#size' => 75,
	'#maxlength' => 20,
	);
	$form['to_play']['author'] = array(
	'#type' => 'textfield',
	'#title' => t('Author'),
	'#required' => TRUE,
	'#default_value' => "",
	'#description' => "Write the author",
	'#size' => 75,
	'#maxlength' => 40,
	);



return $form;
}


/**
* Función de envío del formulario forms_forcontu_form2
*/
function forms_ofertas_listado_submit($form, &$form_state){
	
}



