<?php
/**
 * Variable example.
 */

/**
 * Implements hook_variable_realm_info()
 */
function variable_mails_variable_realm_info() {
  $realm['example'] = array(
    'title' => t('Example'),
    'weight' => 10,
    'store class' => 'VariableStoreRealmStore',
    'keys' => array(
      'first' => t('First example'),
      'second' => t('Second example'),
    ),
  );
  return $realm;
}

/**
 * Implements hook_menu().
 */
function variable_mails_menu() {
  $items['admin/config/system/variable_mails'] = array(
    'title' => 'Ofertas: Variables mails',
    'description' => 'Formulario de configuración de mails.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_group_form', 'variable_mails'),
    'access arguments' => array('administer site configuration'),
  );
  
  return $items;
}

/**
 * Variable example realm page.
 *
 * Will switch to given realm and display variables.
 */
function variable_mails_page_list() {
  variable_include();
  $list = variable_list_group('site_information') + variable_list_group('variable_mails_creacion');
  foreach ($list as $name => $variable) {
    $build[$name] = array(
      '#type' => 'item',
      '#title' => $variable['title'],
      '#markup' => variable_format_value($variable),
    );
  }
  return $build;
}

/**
 * Variable example realm page.
 *
 * Will switch to given realm and display variables.
 */
function variable_mails_page_realm($realm, $key) {
  // Initialize realm from variable store.
  $variables = variable_store($realm, $key);
  // Set at least one variable for the realm
  $variables += array('site_name' => 'Variable example realm');
  variable_realm_add($realm, $key, $variables);
  variable_realm_switch($realm, $key);
  return variable_mails_page_list();
}

